# Generated by Lexis from Ossie dataset 'customer'.
# Customer dimension with demographic information

view: customer {
  sql_table_name: tpcds.public.customer ;;

  dimension: c_customer_sk {
    description: "Surrogate key for customer"
    primary_key: yes
    sql: ${TABLE}.c_customer_sk ;;
  }

  dimension: c_customer_id {
    description: "Business key for customer"
    tags: ["customer ID", "customer number"]
    sql: ${TABLE}.c_customer_id ;;
  }

  dimension: c_first_name {
    description: "Customer first name"
    sql: ${TABLE}.c_first_name ;;
  }

  dimension: c_last_name {
    description: "Customer last name"
    sql: ${TABLE}.c_last_name ;;
  }

  dimension: customer_full_name {
    description: "Customer full name (computed field)"
    tags: ["full name", "customer name"]
    sql: c_first_name || ' ' || c_last_name ;;
  }

  dimension: c_email_address {
    description: "Customer email address"
    tags: ["email", "contact"]
    sql: ${TABLE}.c_email_address ;;
  }

  # Denominator of metric 'customer_lifetime_value'.
  measure: customer_lifetime_value_denominator {
    type: count_distinct
    hidden: yes
    sql: ${TABLE}.c_customer_sk ;;
  }
}
