# Generated by Lexis from Ossie dataset 'date_dim'.
# Date dimension with calendar attributes

view: date_dim {
  sql_table_name: tpcds.public.date_dim ;;

  dimension: d_date_sk {
    description: "Surrogate key for date"
    primary_key: yes
    sql: ${TABLE}.d_date_sk ;;
  }

  # Ossie field 'd_date'; reference it as ${date_dim.d_date}.
  dimension_group: d {
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    convert_tz: no
    datatype: date
    description: "Actual date value"
    tags: ["date", "calendar date"]
    sql: ${TABLE}.d_date ;;
  }

  dimension: d_year {
    description: "Year"
    tags: ["year"]
    sql: ${TABLE}.d_year ;;
  }

  dimension: d_quarter_name {
    description: "Quarter name (e.g., 2024Q1)"
    tags: ["quarter", "fiscal quarter"]
    sql: ${TABLE}.d_quarter_name ;;
  }

  dimension: d_month_name {
    description: "Month name"
    tags: ["month"]
    sql: ${TABLE}.d_month_name ;;
  }
}
