# Generated by Lexis from Ossie dataset 'item'.
# Item/Product dimension with product attributes

view: item {
  sql_table_name: tpcds.public.item ;;

  dimension: i_item_sk {
    description: "Surrogate key for item"
    primary_key: yes
    sql: ${TABLE}.i_item_sk ;;
  }

  dimension: i_item_id {
    description: "Business key for item"
    tags: ["item ID", "product ID", "SKU"]
    sql: ${TABLE}.i_item_id ;;
  }

  dimension: i_item_desc {
    description: "Item description"
    tags: ["product description", "item name"]
    sql: ${TABLE}.i_item_desc ;;
  }

  dimension: i_brand {
    description: "Brand name"
    tags: ["brand", "manufacturer"]
    sql: ${TABLE}.i_brand ;;
  }

  dimension: i_category {
    description: "Item category"
    tags: ["product category", "department"]
    sql: ${TABLE}.i_category ;;
  }

  dimension: i_current_price {
    description: "Current price of the item"
    tags: ["price", "list price"]
    sql: ${TABLE}.i_current_price ;;
  }
}
