# Generated by Lexis from Ossie dataset 'store'.
# Store dimension with location and store attributes

view: store {
  sql_table_name: tpcds.public.store ;;

  dimension: s_store_sk {
    description: "Surrogate key for store"
    primary_key: yes
    sql: ${TABLE}.s_store_sk ;;
  }

  dimension: s_store_id {
    description: "Business key for store"
    tags: ["store ID", "store number"]
    sql: ${TABLE}.s_store_id ;;
  }

  dimension: s_store_name {
    description: "Store name"
    tags: ["store name", "location name"]
    sql: ${TABLE}.s_store_name ;;
  }

  dimension: s_city {
    description: "City where store is located"
    tags: ["city", "location"]
    sql: ${TABLE}.s_city ;;
  }

  dimension: s_state {
    description: "State where store is located"
    tags: ["state", "region"]
    sql: ${TABLE}.s_state ;;
  }

  dimension: s_number_employees {
    description: "Number of employees at the store"
    tags: ["employee count", "staff size"]
    sql: ${TABLE}.s_number_employees ;;
  }

  # Denominator of metric 'store_productivity'.
  measure: store_productivity_denominator {
    type: sum
    hidden: yes
    sql: ${TABLE}.s_number_employees ;;
  }
}
