# Generated by Lexis from Ossie dataset 'store_sales'.
# Fact table containing all store sales transactions

view: store_sales {
  sql_table_name: tpcds.public.store_sales ;;

  # Ossie primary_key is composite ['ss_item_sk', 'ss_ticket_number']; LookML allows only one primary_key dimension, so it is synthesized as a concatenation.
  # Non-string key columns may need an explicit CAST on your warehouse.
  dimension: lexis_primary_key {
    primary_key: yes
    hidden: yes
    sql: ${TABLE}.ss_item_sk || '-' || ${TABLE}.ss_ticket_number ;;
  }

  dimension: ss_sold_date_sk {
    description: "Foreign key to date dimension"
    tags: ["sale date", "transaction date"]
    sql: ${TABLE}.ss_sold_date_sk ;;
  }

  dimension: ss_item_sk {
    description: "Foreign key to item dimension"
    tags: ["product", "item"]
    sql: ${TABLE}.ss_item_sk ;;
  }

  dimension: ss_customer_sk {
    description: "Foreign key to customer dimension"
    tags: ["customer", "buyer"]
    sql: ${TABLE}.ss_customer_sk ;;
  }

  dimension: ss_store_sk {
    description: "Foreign key to store dimension"
    tags: ["store", "location"]
    sql: ${TABLE}.ss_store_sk ;;
  }

  dimension: ss_quantity {
    description: "Quantity of items sold"
    tags: ["units sold", "quantity"]
    sql: ${TABLE}.ss_quantity ;;
  }

  dimension: ss_sales_price {
    description: "Sales price per unit"
    tags: ["unit price", "price"]
    sql: ${TABLE}.ss_sales_price ;;
  }

  dimension: ss_ext_sales_price {
    description: "Extended sales price (quantity * price)"
    tags: ["total price", "line total"]
    sql: ${TABLE}.ss_ext_sales_price ;;
  }

  dimension: ss_net_profit {
    description: "Net profit from the sale"
    tags: ["profit", "margin"]
    sql: ${TABLE}.ss_net_profit ;;
  }

  # Referenced by a join, key or metric but not declared as an Ossie field.
  dimension: ss_ticket_number {
    hidden: yes
    sql: ${TABLE}.ss_ticket_number ;;
  }

  measure: total_sales {
    type: sum
    description: "Total sales revenue across all transactions"
    tags: ["total revenue", "gross sales", "sales amount"]
    sql: ${TABLE}.ss_ext_sales_price ;;
  }

  measure: total_profit {
    type: sum
    description: "Total net profit from store sales"
    tags: ["net profit", "total earnings", "profit"]
    sql: ${TABLE}.ss_net_profit ;;
  }

  measure: sales_by_brand {
    type: sum
    description: "Total sales by brand (requires grouping by item.i_brand)"
    tags: ["brand sales", "brand performance", "brand revenue"]
    sql: ${TABLE}.ss_ext_sales_price ;;
  }

  # Cross-view ratio: valid only in explores joining customer, store_sales.
  measure: customer_lifetime_value {
    type: number
    description: "Average lifetime sales value per customer"
    tags: ["CLV", "LTV", "customer value", "lifetime revenue"]
    sql: ${store_sales.total_sales} / ${customer.customer_lifetime_value_denominator} ;;
  }

  # Cross-view ratio: valid only in explores joining store, store_sales.
  measure: store_productivity {
    type: number
    description: "Sales per employee across stores"
    tags: ["sales per employee", "employee productivity", "revenue per employee"]
    sql: ${store_sales.total_sales} / NULLIF(${store.store_productivity_denominator}, 0) ;;
  }
}
